// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AdventureWorks.Domain.Models;

public partial class TableLog
{
    public int LogID { get; set; }

    public string EventVal { get; set; } = null!;

    public DateTime EventDate { get; set; }

    public string ChangedBy { get; set; } = null!;
}